FROM ngchm/rstudio-ngchm:latest

RUN apt-get update \
 && apt-get -y install libbz2-dev libpng-dev libjpeg-dev liblzma-dev \
 && apt-get -y clean

RUN Rscript -e 'install.packages("BiocManager")' -e 'BiocManager::install(version="3.10")'

RUN Rscript -e 'BiocManager::install("TCGAbiolinks")'


