ARG RSTUDIOPRECORE=ngchm/rstudio-ngchm-pre-core

FROM ${RSTUDIOPRECORE}

RUN apt-get update \
 && apt-get -y install libbz2-dev libpng-dev libjpeg-dev liblzma-dev \
 && apt-get -y clean

RUN Rscript -e "options(Ncpus=`nproc`)" -e 'install.packages("BiocManager")' -e 'BiocManager::install(version="3.10")'

RUN Rscript -e "options(Ncpus=`nproc`)" -e 'install.packages("purrrogress")'

RUN Rscript -e "options(Ncpus=`nproc`)" -e 'BiocManager::install("TCGAbiolinks")'

RUN Rscript -e "options(Ncpus=`nproc`)" -e 'BiocManager::install("rhdf5")'

RUN Rscript -e 'missing <- setdiff(c("BiocManager", "purrrogress", "TCGAbiolinks", "rhdf5"), installed.packages()[,"Package"]); \
                if (length(missing) > 0) stop (paste("Some R packages failed to install: ", paste(missing, collapse=", ")), call.=FALSE)'
